services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-mydb}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION:-col1}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your-gemini-key}
      - API_KEY=${API_KEY:-your-api-key}
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    working_dir: /app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY:-your-api-key}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
    working_dir: /app
    restart: unless-stopped 